name: Check Code Style

on:
  push:
  pull_request:
    paths:
      - '**.php'
      - pint.json

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: pint

      - name: Run Pint
        run: ./vendor/bin/pint --test
