name: Check Code Style On Pull Request

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        paths:
            - "**.php"
            - pint.json

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.4
                  extensions: json, dom, curl, libxml, mbstring
                  coverage: none
                  tools: pint

            - name: Install composer dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: highest

            - name: Run Pint
              run: ./vendor/bin/pint --diff=main --test
